### ISSUE TITLE
Problème pour lancer le visualiser 

### ISSUE THREAD

**Issue by malatini42** [o-reo/push_swap_visualizer#11]
Hello, j'essaie de lancer le visualiseur sur mon mac mais j'ai cette erreur : 
Traceback (most recent call last):
  File "pyviz.py", line 225, in <module>
    gui = PsGui(root)

Est-ce que tu saurais comment mettre à jour le script pour que ça (re) fonctionne s'il-te-plait ?
Merci

**Comment by IsCoffeeTho** [comment]
Translation:

Hello, I am trying to launch the viewer on my mac but I have this error:
```
Traceback (most recent call last):
   File "pyviz.py", line 225, in
   gui = PsGui(root)
```
 Do you know how to update the script so that it (re)works please?
 Thanks

**Comment by o-reo** [comment]
Hi !
Sorry for the delay, you should use the C++ version that is maintained.
I could help but your put only the first two lines of the error message so it's not helping.

**Comment by IsCoffeeTho** [comment]
> Hi ! Sorry for the delay, you should use the C++ version that is maintained. I could help but your put only the first two lines of the error message so it's not helping.

would it be a chore to suply a link?
