### ISSUE TITLE
Cannot compile on ARM architecture

### ISSUE THREAD

**Issue by lucas-ht** [o-reo/push_swap_visualizer#17]
Hello,
I cannot compile with a mac m1, I tried to check the Makefile but cannot find anything related to CPU architecture. Here's the log:
Thank you!
``` make
[ 97%] Linking CXX executable ../bin/visualizer
ld: warning: ignoring file ../_deps/imgui-sfml-build/libImGui-SFML.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "ImGui::BeginChild(char const*, ImVec2 const&, bool, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SliderFloat(char const*, float*, float, float, char const*, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::End()", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::ProcessEvent(sf::Event const&)", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::Init(sf::RenderWindow&, bool)", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::Render(sf::RenderTarget&)", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::Update(sf::RenderWindow&, sf::Time)", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::Shutdown()", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::Text(char const*, ...)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::Begin(char const*, bool*, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::GetIO()", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::Button(char const*, ImVec2 const&)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::EndChild()", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::InputInt(char const*, int*, int, int, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SameLine(float, float)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::InputText(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int, int (*)(ImGuiInputTextCallbackData*), void*)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SliderInt(char const*, int*, int, int, char const*, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/visualizer] Error 1
make[1]: *** [src/CMakeFiles/visualizer.dir/all] Error 2
make: *** [all] Error 2```

**Comment by o-reo** [comment]
I think it's due to the ImGui SFML dependencies. Either IMGUI sfml does not support M1 or the wrong version is downloaded using CMake

**Comment by yazukii** [comment]
I had the same issue and i managed to solve it by installing sfml `brew install sfml` then it compiled. However upon launching the executable i was prompted with `zsh: bad CPU type in executable: ./bin/visualizer` i then solved this by installing Rosetta 2 `softwareupdate --install-rosetta`

**Comment by lucas-ht** [comment]
> I had the same issue and i managed to solve it by installing sfml `brew install sfml` then it compiled. However upon launching the executable i was prompted with `zsh: bad CPU type in executable: ./bin/visualizer` i then solved this by installing Rosetta 2 `softwareupdate --install-rosetta`

I tested your method but unfortunately, it didn't work for me, It still throws the same error message

**Comment by yazukii** [comment]
Did you do `cmake ..` again after installing sfml?

**Comment by yazukii** [comment]
> > I had the same issue and i managed to solve it by installing sfml `brew install sfml` then it compiled. However upon launching the executable i was prompted with `zsh: bad CPU type in executable: ./bin/visualizer` i then solved this by installing Rosetta 2 `softwareupdate --install-rosetta`
> 
> I tested your method but unfortunately, it didn't work for me, It still throws the same error message

Did you do `cmake ..` again after installing sfml?

**Comment by lucas-ht** [comment]
> > > I had the same issue and i managed to solve it by installing sfml `brew install sfml` then it compiled. However upon launching the executable i was prompted with `zsh: bad CPU type in executable: ./bin/visualizer` i then solved this by installing Rosetta 2 `softwareupdate --install-rosetta`
> > 
> > 
> > I tested your method but unfortunately, it didn't work for me, It still throws the same error message
> 
> Did you do `cmake ..` again after installing sfml?

Yes, I rebooted my computer and re-cloned the repo

**Comment by lucas-ht** [comment]
> > > > I had the same issue and i managed to solve it by installing sfml `brew install sfml` then it compiled. However upon launching the executable i was prompted with `zsh: bad CPU type in executable: ./bin/visualizer` i then solved this by installing Rosetta 2 `softwareupdate --install-rosetta`
> > > 
> > > 
> > > I tested your method but unfortunately, it didn't work for me, It still throws the same error message
> > 
> > 
> > Did you do `cmake ..` again after installing sfml?
> 
> Yes, I rebooted my computer and re-cloned the repo

It was a problem on my side, I had a custom version of brew installed, thank you for your help ! I managed to fix it 💯

**Comment by yazukii** [comment]
> > > > > I had the same issue and i managed to solve it by installing sfml `brew install sfml` then it compiled. However upon launching the executable i was prompted with `zsh: bad CPU type in executable: ./bin/visualizer` i then solved this by installing Rosetta 2 `softwareupdate --install-rosetta`
> > > > 
> > > > 
> > > > I tested your method but unfortunately, it didn't work for me, It still throws the same error message
> > > 
> > > 
> > > Did you do `cmake ..` again after installing sfml?
> > 
> > 
> > Yes, I rebooted my computer and re-cloned the repo
> 
> It was a problem on my side, I had a custom version of brew installed, thank you for your help ! I managed to fix it 💯

Nice!

**Comment by Hunam6** [comment]
I ran `brew install sfml`, rebooted my computer, removed the repo, recloned, reinstalled but still, it crashes at 97% with the same error message.

MacOS Ventura 13.2.1 on M1.

```
[ 97%] Linking CXX executable ../bin/visualizer
ld: warning: ignoring file ../_deps/imgui-sfml-build/libImGui-SFML.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "ImGui::BeginChild(char const*, ImVec2 const&, bool, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SliderFloat(char const*, float*, float, float, char const*, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::End()", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::ProcessEvent(sf::Event const&)", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::Init(sf::RenderWindow&, bool)", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::Render(sf::RenderTarget&)", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::Update(sf::RenderWindow&, sf::Time)", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SFML::Shutdown()", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::Text(char const*, ...)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::Begin(char const*, bool*, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::GetIO()", referenced from:
      Gui::loop() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::Button(char const*, ImVec2 const&)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::EndChild()", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::InputInt(char const*, int*, int, int, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SameLine(float, float)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::InputText(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int, int (*)(ImGuiInputTextCallbackData*), void*)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
  "ImGui::SliderInt(char const*, int*, int, int, char const*, int)", referenced from:
      Gui::_updateControls() in libVisualizerLib.a(gui.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/visualizer] Error 1
make[1]: *** [src/CMakeFiles/visualizer.dir/all] Error 2
make: *** [all] Error 2
```
