### ISSUE TITLE
CTRL+A enables entering text in a slider

### ISSUE THREAD

**Issue by Noapoleon** [o-reo/push_swap_visualizer#18]
I was trying to reproduce a weird behavior of the visualizer for quite a bit and I finally managed to consistantly make it work.
Pressing ctrl+a allows entering text in a slider as if it was a text field.
I'm guessing it's selecting the whole UI even though we can't see it.
But after selecting everything clicking once on a slider will allow normal keyboard input.
This is convenient for the speed slider so we can set it at more than 500/s but if a number too large in inputed it will crash the visualizer.

**Comment by o-reo** [comment]
Hi, it's almost an unexpected feature. I don't plan to fix it.
