### ISSUE TITLE
It doesn't work without printing list at start & end

### ISSUE THREAD

**Issue by kalunik** [o-reo/push_swap_visualizer#2]
I gave to visulizer number 0..3 so it fails
<img width="916" alt="Screen Shot 2021-09-23 at 4 00 41 PM" src="https://user-images.githubusercontent.com/33860048/134512371-3f87e601-1d82-4ac9-a63e-e8beced26616.png">
Then I tried to print list before sort and after sort, so I get this
<img width="872" alt="Screen Shot 2021-09-23 at 4 03 12 PM" src="https://user-images.githubusercontent.com/33860048/134512721-5569f978-0b9a-4748-a973-59a7d122b080.png">
And it 's work good. And show all iterations right. Why it doesn't work without print list before & after?

**Comment by o-reo** [comment]
Hi, I hope you were able to finish push swap despite this bug.
It's the first time I am hearing this. 
You could try the new C++ version :)

**Comment by kalunik** [comment]
Yeah, I'd passed the project. So I don't really remember the solution, and my supposed I'd missed up empty write somewhere or so
