### ISSUE TITLE
Compile for OSX

### ISSUE THREAD

**Issue by o-reo** [o-reo/push_swap_visualizer#5]
I work only on Linux so if someone can compile the project on OSX (ARM + AMD) I would gladly publish it in the releases :)

**Comment by LeonMoreno** [comment]
Hello.

First, thank you for your great work, it really helps us a lot for the project. It is an indispensable tool.

machine configuration:
Operating System: Arch Linux                      
          Kernel: Linux 5.16.15-arch1-1
    Architecture: x86-64
 Hardware Vendor: Apple I
gcc version 11.2.0 (GCC) 

The following is the output of make which produces the following errors.

[make.txt](https://github.com/o-reo/push_swap_visualizer/files/8422915/make.txt)

**Comment by o-reo** [comment]
Hi @LeonMoreno.
Thanks for the feedback, I'll have to dig into that !

**Comment by Mikastiv** [comment]
I found what didn't work on those systems:
- The Queues constructor doesn't like cstring to std::string conversion for some reasons. It works like this
`{std::string("sa"), COMMAND::SA},   ...`
- The -Werror flag raises errors with .c_str() for the text gui elements. Like https://github.com/o-reo/push_swap_visualizer/blob/547daa640f8d0bff1ff5fa6053d4a878777463b8/src/gui.cpp#L114 and https://github.com/o-reo/push_swap_visualizer/blob/547daa640f8d0bff1ff5fa6053d4a878777463b8/src/gui.cpp#L120
- The project can't find the SFML headers. I'm not a CMake pro so I don't know how to fix it with CMake. I just installed the library and added the include folder as a flag

Everything compiled and the program works fine after that

**Comment by Mikastiv** [comment]
I would add also on the 42 school's monitors, the GUI elements are very small because Mac's monitor have a very high resolution

**Comment by Mikastiv** [comment]
> I found what didn't work on those systems:
> 
>     * The Queues constructor doesn't like cstring to std::string conversion for some reasons. It works like this
>       `{std::string("sa"), COMMAND::SA},   ...`
> 
>     * The -Werror flag raises errors with .c_str() for the text gui elements. Like https://github.com/o-reo/push_swap_visualizer/blob/547daa640f8d0bff1ff5fa6053d4a878777463b8/src/gui.cpp#L114
>        and https://github.com/o-reo/push_swap_visualizer/blob/547daa640f8d0bff1ff5fa6053d4a878777463b8/src/gui.cpp#L120
> 
>     * The project can't find the SFML headers. I'm not a CMake pro so I don't know how to fix it with CMake. I just installed the library and added the include folder as a flag
> 
> 
> Everything compiled and the program works fine after that

For the -Werror, I found that to use std::string with ImGui it's done like printf:
`ImGui::Text("%s", status.c_str());`

**Comment by Mikastiv** [comment]
Well, Im enjoying working on this issue 😄 

I made a pull request #6 for 2 fixes.

I can't wrap my head around CMake, I give up for the last issue

**Comment by o-reo** [comment]
Thanks Miskativ for your pulls :)
